name: Build Tracy binaries and 3p-package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AUTOBUILD_VARIABLES_FILE: ${{github.workspace}}/build-variables/variables
  EXTRA_ARGS: -DFMODSTUDIO=Off -DUSE_KDU=Off
jobs:
  build-tracy:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Integrate vcpkg
      run: vcpkg integrate install
    - name: Get the repo
      uses: actions/checkout@v3
      with:
        repository: beqjanus/tracy
        path: tracy
        fetch-depth: 0
    - name: debug dump tree
      run: tree ${{github.workspace}}\tracy
    - name: checkout the most recent tag
      run: |
        $tracy_version = & { Push-Location ${{github.workspace}}\tracy;git fetch --tags; git describe --tags --abbrev=0}
        echo "Using Tracy version $tracy_version"
        # Checkout latest tag
        git checkout $tracy_version
    - name: Profiler GUI Release
      run: msbuild ${{github.workspace}}\tracy\profiler\build\win32\Tracy.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Update utility Release
      run: msbuild ${{github.workspace}}\tracy\update\build\win32\update.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Capture utility Release
      run: msbuild ${{github.workspace}}\tracy\capture\build\win32\capture.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Csvexport utility Release
      run: msbuild ${{github.workspace}}\tracy\csvexport\build\win32\csvexport.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Import-chrome utility Release
      run: msbuild ${{github.workspace}}\tracy\import-chrome\build\win32\import-chrome.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Library
      run: msbuild ${{github.workspace}}\tracy\library\win32\TracyProfiler.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Package binaries
      run: |
        cd ${{github.workspace}}\tracy
        mkdir bin
        mkdir bin\dev
        copy profiler\build\win32\x64\Release\Tracy.exe bin
        copy update\build\win32\x64\Release\update.exe bin
        copy capture\build\win32\x64\Release\capture.exe bin
        copy import-chrome\build\win32\x64\Release\import-chrome.exe bin
        copy csvexport\build\win32\x64\Release\csvexport.exe bin
        copy library\win32\x64\Release\TracyProfiler.dll bin\dev
        copy library\win32\x64\Release\TracyProfiler.lib bin\dev
        7z a Tracy.7z bin
    - name: install autobuild
      run: pip3 install git+https://github.com/Nicky-D/autobuild@main_nd

    - name: install llbase
      run: pip3 install llbase
    - name: Checkout build var
      uses: actions/checkout@v3
      with:
        repository: FirestormViewer/fs-build-variables
        path: build-variables
    - name: package the 3p-archive
      run: |
        autobuild build --config-file=autobuild.xml
        autobuild package --config-file=autobuild.xml
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: Tracy-Artifacts
        path: |
          tracy\Tracy.7z
          *.bz2

